CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE categories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title text NOT NULL,
        description text NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_categories PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE companies (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        address text NOT NULL,
        phone_number text NOT NULL,
        inn text NOT NULL,
        CONSTRAINT pk_companies PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE customers (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        email text NOT NULL,
        address text NOT NULL,
        phone_number text NOT NULL,
        location text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_customers PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE company_branches (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        address text NOT NULL,
        phone_number text NOT NULL,
        location text NOT NULL,
        company_id integer NOT NULL,
        CONSTRAINT pk_company_branches PRIMARY KEY (id),
        CONSTRAINT fk_company_branches_companies_company_id FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE carts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        customer_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_carts PRIMARY KEY (id),
        CONSTRAINT fk_carts_customers_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE orders (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        customer_id integer NOT NULL,
        branch_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        product_count integer NOT NULL,
        total_price numeric NOT NULL,
        status integer NOT NULL,
        company_branch_id integer NOT NULL,
        CONSTRAINT pk_orders PRIMARY KEY (id),
        CONSTRAINT fk_orders_company_branches_company_branch_id FOREIGN KEY (company_branch_id) REFERENCES company_branches (id) ON DELETE CASCADE,
        CONSTRAINT fk_orders_customers_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE products (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        description text NOT NULL,
        price numeric NOT NULL,
        category_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        quantity integer NOT NULL,
        branch_id integer NOT NULL,
        product_image text NOT NULL,
        created_by integer,
        company_branch_id integer NOT NULL,
        CONSTRAINT pk_products PRIMARY KEY (id),
        CONSTRAINT fk_products_categories_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
        CONSTRAINT fk_products_company_branches_company_branch_id FOREIGN KEY (company_branch_id) REFERENCES company_branches (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE payments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        status integer NOT NULL,
        CONSTRAINT pk_payments PRIMARY KEY (id),
        CONSTRAINT fk_payments_orders_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE cart_items (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        cart_id integer NOT NULL,
        product_id integer NOT NULL,
        quantity integer NOT NULL,
        CONSTRAINT pk_cart_items PRIMARY KEY (id),
        CONSTRAINT fk_cart_items_carts_cart_id FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
        CONSTRAINT fk_cart_items_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE comments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        content text NOT NULL,
        customer_id integer NOT NULL,
        product_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        star_rating integer NOT NULL,
        CONSTRAINT pk_comments PRIMARY KEY (id),
        CONSTRAINT fk_comments_customers_customer_id FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
        CONSTRAINT fk_comments_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE TABLE order_items (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        order_id integer NOT NULL,
        product_id integer NOT NULL,
        quantity integer NOT NULL,
        unit_price numeric NOT NULL,
        CONSTRAINT pk_order_items PRIMARY KEY (id),
        CONSTRAINT fk_order_items_orders_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
        CONSTRAINT fk_order_items_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_cart_items_cart_id ON cart_items (cart_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_cart_items_product_id ON cart_items (product_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE UNIQUE INDEX ix_carts_customer_id ON carts (customer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_comments_customer_id ON comments (customer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_comments_product_id ON comments (product_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_company_branches_company_id ON company_branches (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_order_items_order_id ON order_items (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_order_items_product_id ON order_items (product_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_orders_company_branch_id ON orders (company_branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_orders_customer_id ON orders (customer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE UNIQUE INDEX ix_payments_order_id ON payments (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_products_category_id ON products (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    CREATE INDEX ix_products_company_branch_id ON products (company_branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921065441_initial') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260921065441_initial', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921074957_FixCompanyBranchIdProperty') THEN
    ALTER TABLE products DROP COLUMN branch_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260921074957_FixCompanyBranchIdProperty') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260921074957_FixCompanyBranchIdProperty', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260925091037_initalCreatUpdateCompanyBranchEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260925091037_initalCreatUpdateCompanyBranchEntity', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260925092856_initalCreatUpdateCompanyBranchEntity111') THEN
    ALTER TABLE orders DROP COLUMN branch_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260925092856_initalCreatUpdateCompanyBranchEntity111') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260925092856_initalCreatUpdateCompanyBranchEntity111', '8.0.0');
    END IF;
END $EF$;
COMMIT;

